# Generated by Django 4.0.4 on 2022-05-07 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cameras', models.IntegerField()),
                ('slug', models.SlugField(max_length=10000, unique=True)),
                ('information', models.TextField(max_length=2000)),
                ('filming', models.TextField(max_length=1000)),
                ('selfie', models.TextField(max_length=100)),
                ('stabilization', models.TextField(max_length=500)),
                ('filming_selfie', models.TextField(max_length=200)),
                ('stabilization_selfie', models.TextField(max_length=500)),
                ('attributes', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images', verbose_name='تصویر')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='category_obshen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images', verbose_name='تصویر')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='connections_labtop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usb', models.IntegerField()),
                ('type_c', models.IntegerField()),
                ('hdmi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='labtop_body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_material', models.TextField(max_length=1000)),
                ('slug', models.SlugField(max_length=10000, unique=True)),
                ('weight', models.IntegerField()),
                ('sim_card', models.TextField(max_length=100)),
                ('information', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=10000, unique=True)),
                ('internal_memory', models.TextField(max_length=300, verbose_name='حافظه داخلی')),
                ('memory_port', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='mobile_body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_material', models.TextField(max_length=1000)),
                ('slug', models.SlugField(max_length=10000, unique=True)),
                ('weight', models.IntegerField()),
                ('dimensions', models.FloatField(max_length=100, verbose_name='ابعاد')),
                ('sim_card', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mobile_screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.TextField(max_length=550, verbose_name='صفحه نمایش')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('screen_type', models.TextField(max_length=200, verbose_name='نوع صفحه نمایش')),
                ('dimensions', models.FloatField(max_length=100, verbose_name='ابعاد')),
                ('refresh_rate', models.TextField(max_length=500, verbose_name='نرخ نوسازی صفحه نمایش')),
                ('screen_saver', models.TextField(max_length=550, null=True, verbose_name='محافظ صفحه نمایش')),
            ],
        ),
        migrations.CreateModel(
            name='processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip', models.TextField(max_length=500)),
                ('graphic_chip', models.TextField(max_length=500)),
                ('information', models.TextField(max_length=2000)),
                ('slug', models.SlugField(max_length=10000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jack', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=10000, unique=True)),
                ('stereo', models.BooleanField(default=True)),
                ('sound_volume', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('desc', models.TextField(max_length=500)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('p', 'publish'), ('n', 'draft')], max_length=1)),
                ('photo', models.ImageField(upload_to='images/')),
                ('cate_obshen', models.ManyToManyField(related_name='category', to='blog.category_obshen')),
                ('category', models.ManyToManyField(related_name='post', to='blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=200, verbose_name='نام گوشی')),
                ('image', models.ImageField(upload_to='images', verbose_name='تصویر')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('desc', models.TextField(verbose_name='توضیحات')),
                ('publication_date', models.DateTimeField(verbose_name='زمان انتشار گوشی')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='قیمت')),
                ('color_phone', models.TextField(max_length=2000)),
                ('operating_system', models.TextField(max_length=300, verbose_name='سیستم عامل')),
                ('battery', models.IntegerField()),
                ('charging_speed', models.IntegerField()),
                ('information', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('p', 'publish'), ('n', 'draft')], max_length=1)),
                ('publication_blog', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('cameras', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='blog.camera')),
                ('cate', models.ManyToManyField(related_name='category', to='blog.category')),
                ('cate_obshen', models.ManyToManyField(related_name='category_obshens', to='blog.category_obshen')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='blog.mobile_body')),
                ('memory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='blog.memory')),
                ('prcs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_processors', to='blog.processor', verbose_name='پردازنده')),
                ('screen_mode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='blog.mobile_screen')),
                ('speaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='blog.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='labtop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labtop_name', models.CharField(max_length=200, verbose_name='نام لب تاپ')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('publication_date', models.DateTimeField(verbose_name='زمان انتشار لب تاپ')),
                ('desc', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images', verbose_name='تصویر')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='قیمت')),
                ('operating_system', models.TextField(max_length=300)),
                ('battery', models.IntegerField()),
                ('charging_speed', models.IntegerField()),
                ('screen', models.TextField(max_length=5000, verbose_name='صفحه نمایش')),
                ('camera', models.TextField(max_length=500)),
                ('finger_print', models.BooleanField(default=False)),
                ('information', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('p', 'publish'), ('n', 'draft')], max_length=1)),
                ('publication_blog', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('cate', models.ManyToManyField(related_name='categorys', to='blog.category')),
                ('cate_obshen', models.ManyToManyField(related_name='category_obshe', to='blog.category_obshen')),
                ('color_labtop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_lobtops', to='blog.color')),
                ('connections', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connections_labtop', to='blog.connections_labtop')),
                ('labtop_processor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processors', to='blog.processor')),
                ('lobtop_speaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lobtop_speakers', to='blog.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField(max_length=700)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reply', models.BooleanField(default=False)),
                ('post_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_key', to='blog.post')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentid', to='blog.comment')),
            ],
        ),
    ]
