# Generated by Django 4.0.4 on 2022-05-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='screen_mode',
        ),
    ]
