# Generated by Django 4.0.4 on 2022-05-07 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_mobile_screen_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='screen_mode',
            field=models.OneToOneField(default=datetime.datetime(2022, 5, 7, 12, 52, 5, 522092, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='screenss', to='blog.mobile_screen'),
            preserve_default=False,
        ),
    ]
