# Generated by Django 4.0.4 on 2022-05-09 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_mobile_screen_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='screen',
            field=models.TextField(default=datetime.datetime(2022, 5, 9, 13, 8, 57, 864565, tzinfo=utc), max_length=5000, verbose_name='صفحه نمایش'),
            preserve_default=False,
        ),
    ]
